### ISSUE TITLE
Adding 22 functional networks in preloaded parcellations

### ISSUE THREAD

**Issue by amsinha9** [rmldj/hcp-utils#1]
Of the preloaded parcellations that come with hcp_utils, hcp.mmp includes 360 regions (180 per hemisphere) plus 19 FreeSurfer subcortical regions, for a total of 379 regions. Along with this parcellation, could the 22 (or 23 if subcortical is included) functional networks described in Glasser et. al. 2016 and shown in the scene file, Glasser_et_al_2016_HCP_MMP1.0_4_SupplementaryNeuroanatomicalResults.scene, from https://balsa.wustl.edu/sceneFile/show/n889 be added as a new preloaded parcellation?

This would be extremely helpful in depicting both the ROIs and corresponding functional networks in 3D surface plot figures for research presentations and papers. It would also be useful for network-level analyses using Glasser parcellation.

**Comment by rmldj** [comment]
Hi,

Please have a look at the thread https://groups.google.com/a/humanconnectome.org/forum/#!msg/hcp-users/all_vvOj1sE/yWjEatR6BwAJ There Glasser comments that the 22 areas do not have clear neurobiological meaning and were used for convenience. 

However, the Cole-Anticevic partition (included in hcp_utils) groups the 360 MMP regions into functional networks. Please have a look at _Cole-Anticevic brain-wide functional networks_ and  _Cole-Anticevic extension of MMP to a parcellation of the subcortical regions_ in https://rmldj.github.io/hcp-utils/parcellation_labels.html. The cortical regions of the latter are identical to the MMP ones but just have different names associated with the functional networks. So I guess that this would be best for what you have in mind.

Romuald

**Comment by amsinha9** [comment]
Romuald,

To clarify, the 360 cortical regions do not truly correspond to the 22 functional networks outlined in the Glasser paper then? Also, to be clear, the Cole-Anticevic functional networks use the exact same regions as in the MMP, but instead group them into 11 functional networks as opposed to 22?

-Anita

**Comment by rmldj** [comment]
As far as I understand (and what I gathered from Matt Glasser's comment on that thread on the hcp-users list which I linked) the 22 regions cannot be strictly interpreted as functional networks. 

The 360 MMP cortical regions can be indeed grouped into the 22 regions but as one of the key authors of that paper somehow did not support using them, it may not be a good idea to include them here. But you may ask on hcp-users for clarification.

> Also, to be clear, the Cole-Anticevic functional networks use the exact same regions as in the MMP, but instead group them into 11 functional networks as opposed to 22?

Yes indeed (12 functional networks).
