### ISSUE TITLE
citing use of package

### ISSUE THREAD

**Issue by amsinha9** [rmldj/hcp-utils#5]
Do you have a preferred citation we should use in publications if we display results of brain figures using hcp-utils?

**Comment by rmldj** [comment]
Thanks! I am really glad that it's useful.
Please cite the github URL of the package.
Btw. I would be happy if at some stage you could e-mail me your paper..

**Comment by amsinha9** [comment]
Yes, once it has been accepted, we will share the paper. Do you know if there is a way to generate half of the 3D brain image to plot the subcortical parcels? We are trying to edit the source code in hcp_utils.py to only show the left hemisphere and the corresponding left parcels. We are wondering if we could edit the function load_surfaces and do something similar to below:

```
for hemisphere, hemisphere_name in [('L', 'left')]:
     elif count==1:
                #meshes[variant] = meshes[variant+'_left']
```

**Comment by rmldj** [comment]
You mean **subcortical**? Then there is no way using hcp_utils as it uses nilearn's surface plot which plots only cortical surfaces (as I discussed in the other issue).

I now remember that once I made some 3d plot with subcortical structures using matplotlib 3d but that was rather ugly and slow. I do not know if I can locate the script...
